# Generated by Django 4.1.7 on 2023-03-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.IntegerField()),
                ("current_balance", models.IntegerField()),
                ("accounter_number", models.IntegerField()),
            ],
        ),
    ]
