# Generated by Django 4.1.7 on 2023-03-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="accounter_number",
            new_name="account_number",
        ),
    ]
