# Generated by Django 4.1.7 on 2023-03-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("transaction_type", models.BooleanField()),
                ("note", models.CharField(max_length=256)),
                ("amount", models.IntegerField()),
                ("account_id", models.CharField(max_length=32)),
            ],
        ),
    ]
